export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR'
export const AUTHENTICATE = 'AUTHENTICATE'
export const CREATE_USER = 'CREATE_USER'
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR'